### ISSUE TITLE
Review legacy TrueOS documentation and add relevent material to Trident website.

### ISSUE THREAD

**Issue by Mrt134** [project-trident/trident-website#12]
There is a large amount of TrueOS documentation that is now legacy with the project change at 18.06. Some of the material might still be relevent to Trident and need to be added to the website.

**Comment by q5sys** [comment]
Link to repo:  https://github.com/project-trident/trident-docs

- Everything has been changed from .RST to .MD
- All references have been changed from TrueOS to Trident.

- Still needs review of everything as Issue states.

**Comment by ManyHeadgear** [comment]
What documentation? I don't see no stinkin' documentation.  Relevant Trident/TrueOS specific docs are not old FreeBSD docs. Configuring Trident with old docs...relevance??? RYEATB

**Comment by q5sys** [comment]
![huh-what](https://user-images.githubusercontent.com/4654247/49610209-e4307d00-f96b-11e8-9e23-ca7060c51605.gif)

**Comment by RodMyers** [comment]
going to close since Project-Trident will be moving to void linux in 2020
