### ISSUE TITLE
www.trident.org uses an invalid security certificate

### ISSUE THREAD

**Issue by mrT55** [project-trident/trident-website#13]
According to firefox when I tried to access https://www.trident.org/downloads/
today (09/04/2018 at 5:40pm EDST) I got the following error:
Your connection is not secure.
www.trident.org uses an invalid security certificate. The certificate is only valid for the following names: *.wpengine.com, wpengine.com Error code: SSL_ERROR_BAD_CERT_DOMAIN

Upon closer look I discovered that the web site does not support https connections.
I was using a link from: https://github.com/project-trident/trident-docs/blob/4e787f2e242c1e185cbe953843c53bd176b7fbf2/install.md
So, either the doc is incorrect or the website needs to be fixed.

**Comment by mrT55** [comment]
When I try:
   http://www.trident.org/downloads/
I get automatically redirected to:
  https://digitalfortress.io/downloads/
   "Oops, This Page Could Not Be Found!"

**Comment by q5sys** [comment]
First off... our website is project-trident.org.  It is not trident.org  

That being said...  if you would like to purchase Trident.org for us, we would be very grateful. ;) lol

However, we're still working on the site, so we haven't gotten certs worked out for everything yet.  Since we are not near an official release yet... that's what's been taking out focus.

**Comment by mrT55** [comment]
OK, so just to point out that the source of that like was from the trident doc page
(see above link). Therefore, the doc page needs an updated link.

**Comment by q5sys** [comment]
So it was.   It's been updated with: https://github.com/project-trident/trident-docs/commit/411773368b1797376d66ee21152ab138a97f05f9

Those docs are a quick converted version of the older TrueOS Docs.  We will be going through them when we have time and they will be replaced.

**Comment by beanpole135** [comment]
Closing issue. 
Link within the old docs has already been updated.
