### ISSUE TITLE
Please doument how to save an install log from the installer

### ISSUE THREAD

**Issue by allentiak** [project-trident/trident-website#36]
Copy of https://github.com/project-trident/trident-installer/issues/47.

It seems to me that this issue belongs to this project, more than to that one?

**Comment by allentiak** [comment]
Ping @beanpole135, @Mrt134?

**Comment by allentiak** [comment]
This would be very helpful for newcomers. (BTW: I am referring to be able to report from an installation on a real machine, not into a VM instance.)

**Comment by beanpole135** [comment]
Closing this old ticket.
Installation logs are available via the installer menu, or can be viewed on the installed system at: 

* /var/log/trident-install.log
