### ISSUE TITLE
Please add instructions on how to download images securely

### ISSUE THREAD

**Issue by allentiak** [project-trident/trident-website#38]
How to verify the signature and the public key?
I think it should be something similar to the "Download Kali Linux Images Securely" section from https://www.kali.org/downloads/...

**Comment by beanpole135** [comment]
Done: https://github.com/project-trident/trident-website/commit/6aeeb370c8db255fe94e5524b43e6a3c38582f4d

**Comment by allentiak** [comment]
Thanks @beanpole135!
