### ISSUE TITLE
Website: Add Handbook Structure

### ISSUE THREAD

**Issue by beanpole135** [project-trident/trident-website#4]
Create page hierarchy for the users handbook.

Important sections:
1. Download/prepare ISO for installation
2. Multi-boot setup
3. Getting Started
4. Other....

**Comment by yater** [comment]
thankfully there is (was) the [PC-BSD (User Guide) Handbook](http://iso.cdn.pcbsd.org/10.3-RELEASE/amd64/docs/html/pcbsd.html) available. this should be a good base to start (fork) the structure from.

**Comment by beanpole135** [comment]
Closing this old ticket.
Use the Community Wiki for Project Trident instead: 
https://github.com/project-trident/trident-docs/wiki
