### ISSUE TITLE
Write Contributor Guide document for Project Trident

### ISSUE THREAD

**Issue by Mrt134** [project-trident/trident-website#7]
Outline and create a Contributor Guide for Project Trident. This is to be done after completing the Style Guide. This document will be written and submitted to the project according to the Style Guide.

**Comment by Mrt134** [comment]
Outline (WIP, will continuously update this post)

**Trident Contributor Guide**

1. Introduction
   - Goal: to explain making contributions to Trident. Increase number of contributors.
   - Quickstart: Simple instruction for GitHub edit and PR (code)
2. Code Contributions
   - Guidelines
   - Process
3. Documentation Contributions
   - Guidelines (link to style guide, but provide quick summary of key elements)
   - Process (GitHub and local workflows)
4. Translation Contributions
   - Explain translation system (TBD)
   - Process
5. Issue Contributions
   - Recommendations
   - Example ticket

**Comment by Mrt134** [comment]
WIP guide:
[trident-contributor-guide.md.txt](https://github.com/project-trident/trident-website/files/2380666/trident-contributor-guide.md.txt)

**Comment by beanpole135** [comment]
Closing this old ticket.
Use the Community Wiki for Project Trident instead:
https://github.com/project-trident/trident-docs/wiki
