### ISSUE TITLE
Bad visibility of text

### ISSUE THREAD

**Issue by samob** [project-trident/trident-website#9]
Wondering if low contrast between fonts and background colours is a way of visually letting people know Trident is not yet available for masses? Because if it is not the case, something should be done to boost visibility of text. My eyes are really struggling to read anything in this "greyed out" setup.

**Comment by q5sys** [comment]
I've darkened the font shade a bit, hopefully that will help.  https://github.com/project-trident/trident-website/commit/6387e7d7fd77cbec8ed658122359549a7754a192
